version: '2'

services:
  gogs:
    container_name: gogs
    restart: always
    image: gogs/gogs-rpi:latest
    ports:
        - "3022:22"
        - "3000:3000"
    volumes:
        - "gogs_data:/data/gogs"
    environment:
        - "RUN_CROND=true"
volumes:
    gogs_data:
        driver: local
